title: Hire Python Developer | Backend & Cloud Expert | Freelance API Architect
description: Need a senior Python developer? I build high-performance backend APIs, cloud architectures, and AI integrations that scale to millions of users with 99.9% uptime. Hire me for your next project.
author: Henrique Lobato
baseurl: ""
url: "https://iklobato.github.io"
social:
  github: iklobato
  linkedin: iklobato-sr-python
  calendly: hlobato/lets-talk
keywords: Hire Python Developer, Senior Backend Engineer, API Architect, AWS Cloud Expert, Django REST API, FastAPI Developer, Kubernetes Specialist, AI Integration, Python Freelancer, Remote Developer, Microservices, Scalable Systems

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Jekyll settings
permalink: pretty
encoding: UTF-8

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - backend_cv_enhanced.md
  - data_engineer_cv_enhanced.md
  - devops_cv_enhanced.md
  - unified_cv_template.md