title: Hire Python Developer | Backend & Cloud Expert | Freelance API Architect
description: Expert Python backend developer building scalable APIs & cloud solutions. 10+ years experience, 99.9% uptime. Let's build your backend today.
author: Henrique Lobato
baseurl: ""
url: "https://iklobato.com"
social:
  github: iklobato
  linkedin: iklobato-sr-python
  calendly: hlobato/lets-talk
keywords: Hire Python Developer, Senior Backend Engineer, API Architect, AWS Cloud Expert, Django REST API, FastAPI Developer, Kubernetes Specialist, AI Integration, Python Freelancer, Remote Developer, Microservices, Scalable Systems

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Jekyll settings
permalink: pretty
encoding: UTF-8

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - backend_cv_enhanced.md
  - data_engineer_cv_enhanced.md
  - devops_cv_enhanced.md
  - unified_cv_template.md