title: Henrique Lobato | Senior Python Developer & Cloud Architect
description: Senior Python Developer, Tech Lead, and Cloud Architect specializing in backend engineering, data pipelines, and DevOps with 10+ years experience.
author: Henrique Lobato
baseurl: ""
url: "https://iklobato.github.io"
social:
  github: iklobato
  linkedin: iklobato-sr-python
keywords: Python Developer, Backend Engineering, Data Engineering, Cloud Architect, DevOps Engineer, AWS, GCP, Django, Flask, FastAPI, Kubernetes, PostgreSQL

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Jekyll settings
permalink: pretty
encoding: UTF-8

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - backend_cv_enhanced.md
  - data_engineer_cv_enhanced.md
  - devops_cv_enhanced.md
  - unified_cv_template.md