title: Henrique Lobato
description: Senior Python Developer | Tech Lead | Cloud Architect
baseurl: ""
url: "https://iklobato.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Jekyll settings
permalink: pretty
encoding: UTF-8

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - backend_cv_enhanced.md
  - data_engineer_cv_enhanced.md
  - devops_cv_enhanced.md
  - unified_cv_template.md